export type Language = { code: string; name: string; english: string };

/** 90 supported regions for automatic UI translation. */
export const LANGUAGES: Language[] = [
  { code: "en", name: "English", english: "English" },
  { code: "pt-BR", name: "Português (Brasil)", english: "Brazilian Portuguese" },
  { code: "pt-PT", name: "Português (Portugal)", english: "European Portuguese" },
  { code: "es", name: "Español", english: "Spanish" },
  { code: "es-MX", name: "Español (México)", english: "Mexican Spanish" },
  { code: "fr", name: "Français", english: "French" },
  { code: "fr-CA", name: "Français (Canada)", english: "Canadian French" },
  { code: "de", name: "Deutsch", english: "German" },
  { code: "it", name: "Italiano", english: "Italian" },
  { code: "nl", name: "Nederlands", english: "Dutch" },
  { code: "pl", name: "Polski", english: "Polish" },
  { code: "ru", name: "Русский", english: "Russian" },
  { code: "uk", name: "Українська", english: "Ukrainian" },
  { code: "tr", name: "Türkçe", english: "Turkish" },
  { code: "ar", name: "العربية", english: "Arabic" },
  { code: "he", name: "עברית", english: "Hebrew" },
  { code: "fa", name: "فارسی", english: "Persian" },
  { code: "hi", name: "हिन्दी", english: "Hindi" },
  { code: "bn", name: "বাংলা", english: "Bengali" },
  { code: "ur", name: "اردو", english: "Urdu" },
  { code: "ta", name: "தமிழ்", english: "Tamil" },
  { code: "te", name: "తెలుగు", english: "Telugu" },
  { code: "mr", name: "मराठी", english: "Marathi" },
  { code: "gu", name: "ગુજરાતી", english: "Gujarati" },
  { code: "kn", name: "ಕನ್ನಡ", english: "Kannada" },
  { code: "ml", name: "മലയാളം", english: "Malayalam" },
  { code: "pa", name: "ਪੰਜਾਬੀ", english: "Punjabi" },
  { code: "ne", name: "नेपाली", english: "Nepali" },
  { code: "si", name: "සිංහල", english: "Sinhala" },
  { code: "th", name: "ไทย", english: "Thai" },
  { code: "vi", name: "Tiếng Việt", english: "Vietnamese" },
  { code: "id", name: "Bahasa Indonesia", english: "Indonesian" },
  { code: "ms", name: "Bahasa Melayu", english: "Malay" },
  { code: "fil", name: "Filipino", english: "Filipino" },
  { code: "km", name: "ភាសាខ្មែរ", english: "Khmer" },
  { code: "lo", name: "ລາວ", english: "Lao" },
  { code: "my", name: "မြန်မာ", english: "Burmese" },
  { code: "ja", name: "日本語", english: "Japanese" },
  { code: "ko", name: "한국어", english: "Korean" },
  { code: "zh-CN", name: "简体中文", english: "Simplified Chinese" },
  { code: "zh-TW", name: "繁體中文", english: "Traditional Chinese" },
  { code: "yue", name: "粵語", english: "Cantonese" },
  { code: "mn", name: "Монгол", english: "Mongolian" },
  { code: "kk", name: "Қазақша", english: "Kazakh" },
  { code: "uz", name: "Oʻzbekcha", english: "Uzbek" },
  { code: "az", name: "Azərbaycan", english: "Azerbaijani" },
  { code: "ka", name: "ქართული", english: "Georgian" },
  { code: "hy", name: "Հայերեն", english: "Armenian" },
  { code: "el", name: "Ελληνικά", english: "Greek" },
  { code: "ro", name: "Română", english: "Romanian" },
  { code: "bg", name: "Български", english: "Bulgarian" },
  { code: "sr", name: "Српски", english: "Serbian" },
  { code: "hr", name: "Hrvatski", english: "Croatian" },
  { code: "bs", name: "Bosanski", english: "Bosnian" },
  { code: "sl", name: "Slovenščina", english: "Slovenian" },
  { code: "sk", name: "Slovenčina", english: "Slovak" },
  { code: "cs", name: "Čeština", english: "Czech" },
  { code: "hu", name: "Magyar", english: "Hungarian" },
  { code: "fi", name: "Suomi", english: "Finnish" },
  { code: "sv", name: "Svenska", english: "Swedish" },
  { code: "no", name: "Norsk", english: "Norwegian" },
  { code: "da", name: "Dansk", english: "Danish" },
  { code: "is", name: "Íslenska", english: "Icelandic" },
  { code: "et", name: "Eesti", english: "Estonian" },
  { code: "lv", name: "Latviešu", english: "Latvian" },
  { code: "lt", name: "Lietuvių", english: "Lithuanian" },
  { code: "sq", name: "Shqip", english: "Albanian" },
  { code: "mk", name: "Македонски", english: "Macedonian" },
  { code: "mt", name: "Malti", english: "Maltese" },
  { code: "ga", name: "Gaeilge", english: "Irish" },
  { code: "cy", name: "Cymraeg", english: "Welsh" },
  { code: "eu", name: "Euskara", english: "Basque" },
  { code: "ca", name: "Català", english: "Catalan" },
  { code: "gl", name: "Galego", english: "Galician" },
  { code: "af", name: "Afrikaans", english: "Afrikaans" },
  { code: "sw", name: "Kiswahili", english: "Swahili" },
  { code: "am", name: "አማርኛ", english: "Amharic" },
  { code: "ha", name: "Hausa", english: "Hausa" },
  { code: "yo", name: "Yorùbá", english: "Yoruba" },
  { code: "ig", name: "Igbo", english: "Igbo" },
  { code: "zu", name: "isiZulu", english: "Zulu" },
  { code: "xh", name: "isiXhosa", english: "Xhosa" },
  { code: "so", name: "Soomaali", english: "Somali" },
  { code: "rw", name: "Kinyarwanda", english: "Kinyarwanda" },
  { code: "mg", name: "Malagasy", english: "Malagasy" },
  { code: "ht", name: "Kreyòl Ayisyen", english: "Haitian Creole" },
  { code: "qu", name: "Runa Simi", english: "Quechua" },
  { code: "gn", name: "Guaraní", english: "Guarani" },
  { code: "mi", name: "Te Reo Māori", english: "Maori" },
  { code: "sm", name: "Gagana Samoa", english: "Samoan" },
  { code: "haw", name: "ʻŌlelo Hawaiʻi", english: "Hawaiian" },
];

export const RTL = new Set(["ar", "he", "fa", "ur"]);
